### ISSUE TITLE
chkcrontab command takes nonexistent file without complaints and exits okay (exitcode=0)

### ISSUE THREAD

**Issue by ye** [lyda/chkcrontab#11]
As seen below, randomly typing a nonexistent filename `chkcrontab` would take it in fine with no complaints and gives an okay exist code (0).

```bash
$ ls -l
total 16
-rw-r--r--  1 ye  staff   120 Nov  7 18:04 Dockerfile
-rw-r--r--  1 ye  staff  2145 Nov  8 11:02 test-crontab
$ chkcrontab ./8e5f63ef-915b-4616-ad90-31a1a590922d
Checking correctness of ./8e5f63ef-915b-4616-ad90-31a1a590922d
$ echo $?
0
$ chkcrontab 
ERROR: No crontab file was specified.
$ echo $?
1
```

It should probably exit with an error exitcode(1) and print out an error message just as if I didn't provide a file or similar. "ERROR: ./8e5f63ef-915b-4616-ad90-31a1a590922d doesn't exist."

**Comment by lyda** [comment]
Valid.  Added in b8ed6c0. Sorry for the delay. Had some personal issues which kept me from this.

**Comment by lyda** [comment]
(this will be in 1.7)

**Comment by ye** [comment]
@lyda you are simply adding a log line, the exit code hasn't been changed if file doesn't exist, has it?

**Comment by lyda** [comment]
If it's a warning it changes the exit code:

```bash
/ # chkcrontab kitten
Checking correctness of kitten
W: File "kitten" does not exist.
W: There were 1 warnings.
See http://goo.gl/7XS9q for more info.
/ # echo $?
1
/ # chkcrontab /dev/null
Checking correctness of /dev/null
/ # echo $?
0
```

I did push out a new version so if you upgrade you can confirm it works as desired. If not let me know.
